# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
